name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - name: Ruff (lint)
        run: ruff check .
      - name: Black (format)
        run: black --check .
      - name: MyPy (types)
        run: |
          mypy src/gui-weather
      - name: Pytest (unit tests)
        run: pytest -q
